version: "3.9"
services:
  frontend:
    build: ./
    volumes:
      - .:/app
  nginx:
    depends_on:
      - frontend
    restart: always
    build: ./nginx
    ports:
      - "7777:80"
    volumes:
      - "/home/thinhbui/Workspaces/Teaching/DevOps/Docker/public:/var/www/html"
      - "nginxdata:/var/www/public_nginx"
volumes:
  nginxdata:
